import { withPayload } from '@payloadcms/next/withPayload'
import type { NextConfig } from 'next'
import path from 'path'
import { fileURLToPath } from 'url'
import { createRequire } from 'module'

const __filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(__filename)
const require = createRequire(import.meta.url)

// Generated by `npm run build:redirects` after a migration. Maps the old
// Eleventy permalinks (/photo/<date_url>/) onto the new canonical slugs.
// Committed to the repo so builds don't need database access.
const legacyRedirects: { source: string; destination: string }[] = require('./redirects.json')

const nextConfig: NextConfig = {
  // Required by the Dockerfile that Payload Cloud builds from.
  output: 'standalone',

  async redirects() {
    return legacyRedirects.map((r) => ({ ...r, permanent: true }))
  },

  webpack: (webpackConfig) => {
    webpackConfig.resolve.extensionAlias = {
      '.cjs': ['.cts', '.cjs'],
      '.js': ['.ts', '.tsx', '.js', '.jsx'],
      '.mjs': ['.mts', '.mjs'],
    }

    return webpackConfig
  },
  turbopack: {
    root: path.resolve(dirname),
  },
}

export default withPayload(nextConfig, { devBundleServerPackages: false })
